### ISSUE TITLE
How can i use this tool chain to build ppc64le osquery  from x86_64

### ISSUE THREAD

**Issue by milind69** [theopolis/build-anywhere#6]
I am trying to build osquery tool for ppc64le , i tried different toolchain versions  but all failing to build
Now I want to try using build-anywhere tool chain  from x86_64 , can i do it ? how can I do it ?

**Comment by theopolis** [comment]
@milind69, let's keep discussion to a single issue for now. I see you've opened one here, on the osquery-toolchain, and on osquery itself. Please be patient and we'll keep discussion organized in a single threat.
